wmata_bus:
  outputs:
    dev:
      dataset: dbtschema
      job_execution_timeout_seconds: 600
      job_retries: 1
      keyfile: secrets/final.json
      location: EU
      method: service-account
      priority: interactive
      project: final-385014
      threads: 1
      type: bigquery
  target: dev